language: cpp
before_script:
- sudo apt install libboost-test-dev libboost-program-options-dev -y
script:
- cmake .
- cmake --build . -- -j8
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - FILE_NAME='ls | grep otus_homework1'
  - echo "FILE_NAME "${FILE_NAME}
