language: cpp
before_script:
- sudo apt install libboost-test-dev libboost-program-options-dev -y
script:
- cmake .
- cmake --build . -- -j8
- cmake --build . --target test
- cmake --build . --target package
before_deploy:
- export DEB_FILE_NAME=$(ls)
- echo "DEB_FILE_NAME ${DEB_FILE_NAME}"
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ls
