language: cpp
before_script:
- sudo apt install libboost-test-dev libboost-program-options-dev -y
script:
- cmake .
- cmake --build . -- -j8
- cmake --build . --target test
- cmake --build . --target package
before_deploy:
- export DEB_FILE_NAME=$(ls *.deb)
deploy:
  provider: script
  file_glob: true
  skip_cleanup: true
  script:
  - curl -T $DEB_FILE_NAME -unikenja:$BINTRAY_API_KEY "https://api.bintray.com/content/nikenja/otus_homework/hw1/$TRAVIS_BUILD_NUMBER/$DEB_FILE_NAME

curl -T <FILE.EXT> -unikenja:<API_KEY> https://api.bintray.com/content/nikenja/otus_homework/<YOUR_COOL_PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>