language: cpp
before_script:
- sudo apt install libboost-test-dev libboost-program-options-dev -y
script:
- cmake .
- cmake --build . -- -j8
- cmake --build . --target test
- cmake --build . --target package
before_deploy:
- export DEB_FILE_NAME=$(ls *.deb)
deploy:
  provider: script
  file_glob: true
  skip_cleanup: true
  script:
  - curl -T $DEB_FILE_NAME -u nikenja:$BINTRAY_API_KEY "https://api.bintray.com/content/nikenja/otus_homework/1/$DEB_FILE_NAME; deb_distribution=trusty; deb_component=main; deb_architecture=amd64; publish=1"
